# Generated by Django 6.0.1 on 2026-06-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_permission_role_rolepermission'),
        ('customerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authApp.role'),
        ),
    ]
