# Generated by Django 6.0.1 on 2026-06-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_customermaster_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermaster',
            name='role',
        ),
    ]
